print("Welcome to Band Name Generator")
print("What's the name of the city you grew up in?")
city_name = input()
print("What's you pet's name?")
pet_name = input()
print("Your Band name could be",city_name,pet_name)
