print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
tip_percentage = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
number_of_people = int(input("How many people to split the bill? "))
print(f"Each person should pay: ${round((1+tip_percentage/100) * total_bill / number_of_people, 2)}")